### ISSUE TITLE
Implement Rename Functionality

### ISSUE THREAD

**Issue by abdel-17** [abdel-17/svelte-file-tree#5]
Use `Enter` as a keyboard shortcut similar to Finder on macOS

**Comment by mustafa0x** [comment]
i think enter should open. like google drive. however im not sure what the best alternative is. f2 works (also like gdrive).

**Comment by abdel-17** [comment]
@mustafa0x what does "open" even mean in this context? expand the folder?

**Comment by mustafa0x** [comment]
Yes, navigate to folder if folder, or open file/document if file.

**Comment by abdel-17** [comment]
I don't think the library should be aware of file-opening functionality. Maybe it could be exposed through an `onaction` prop where you can perform certain tasks when the item is "activated".

**Comment by mustafa0x** [comment]
Agreed. 👍
